### PR TITLE
Move testing folder from bitcoinj to local

### PR DESCRIPTION
**Pull request by lazyGoose**

### CODE REVIEW

**Comment by lazyGoose** [comment]
Bitcoinj recently moved org.bitcoinj.testing package to test classpath.

**Comment by mikehearn** [comment]
Could you take this up with Andreas please? The testing utilities were meant to be in the core package, it doesn't make sense to just copy/paste all that code into Lighthouse. It sounds like that change should be reverted. 

BTW I am not maintaining Lighthouse any more, I do not expect it to work well given the current state of the Bitcoin network.

**Comment by lazyGoose** [comment]
Could I have Andreas's contact information?

**Comment by mikehearn** [comment]
He is the bitcoinj maintainer. You can reach him through the bitcoinj mailing list.

**Pull request closed without merging**
